version: '3'
services:
    redis-db:
        image: redis:alpine
        command: redis-server --appendonly yes
        container_name: local_redis
        restart: unless-stopped
        # network_mode: host        
        ports:
            - '6379:6379'
        volumes:             
        - ./data:/data
    # environment:
    #     - REDIS_REPLICATION_MODE=master            
    #     REDIS_REPLICATION_MODE: The replication mode. Possible values master/slave. No defaults.
    #     REDIS_REPLICA_IP: The replication announce ip. Defaults to $(get_machine_ip) which return the ip of the container.
    #     REDIS_REPLICA_PORT: The replication announce port. Defaults to REDIS_MASTER_PORT_NUMBER.
    #     REDIS_MASTER_HOST: Hostname/IP of replication master (replica node parameter). No defaults.
    #     REDIS_MASTER_PORT_NUMBER: Server port of the replication master (replica node parameter). Defaults to 6379.
    #     REDIS_MASTER_PASSWORD: Password to authenticate with the master (replica node parameter). No defaults. As an alternative, you can mount a file with the password and set the REDIS_MASTER_PASSWORD_FILE variable.