version: '3'
services:
    sql-server-db:
        image: mcr.microsoft.com/mssql/server:${DV_VERSION:-2017-CU8-ubuntu}
        container_name: local_sql_server
        restart: unless-stopped
        network_mode: host
        logging:
            options:
            max-size: 10m
            max-file: "3"
        environment:
            SA_PASSWORD: ${DB_PASSWORD:-my_database}
            ACCEPT_EULA: "Y"
        # ports:
            # - "${DB_PORT:-1433}:1433"
        volumes:             
            - ${DB_DATA_PATH:-./data}:/var/opt/mssql/data