version: '3'
services:
    mongo-db:
        image: mongo:latest
        container_name: local_mongo
        restart: unless-stopped
        # network_mode: host
        env_file:
            - database.env
        # environment:
        #     - POSTGRES_USER=postgres
        #     - POSTGRES_PASSWORD=postgres
        # logging:
        #     options:
        #     max-size: 10m
        #     max-file: "3"
        ports:
            - 27017:27017
        volumes:             
            - ./data:/data/db
            # copy the sql script to create tables
            # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    # mongo-express:
        # image: mongo-express:latest
        # restart: unless-stopped
        # ports:
            # - 8081:8081
        # environment:
            # - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            # - ME_CONFIG_MONGODB_ADMINPASSWORD=root
            # - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            # - ME_CONFIG_MONGODB_SERVER=mongo
            # - ME_CONFIG_MONGODB_PORT=27017            
            # - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
            # - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
            # - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
            # - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
            # - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
        # depends_on:
            # - mongo-db
